#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright (c) 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""Configuration for the hidden-state PPO-Mamba Gorge Chase agent."""


class Config:
    # Map and observation layout.
    MAP_SIZE = 128
    LOCAL_MAP_SIZE = 21
    GLOBAL_MAP_SIZE = 32
    LOCAL_CHANNELS = 7
    GLOBAL_CHANNELS = 6
    SCALAR_DIM = 288
    MAMBA_HIDDEN_DIM = 128

    LOCAL_FLAT_DIM = LOCAL_CHANNELS * LOCAL_MAP_SIZE * LOCAL_MAP_SIZE
    GLOBAL_FLAT_DIM = GLOBAL_CHANNELS * GLOBAL_MAP_SIZE * GLOBAL_MAP_SIZE
    FEATURE_SPLIT_SHAPE = [
        LOCAL_FLAT_DIM,
        GLOBAL_FLAT_DIM,
        SCALAR_DIM,
        MAMBA_HIDDEN_DIM,
    ]
    FEATURE_LEN = sum(FEATURE_SPLIT_SHAPE)
    DIM_OF_OBSERVATION = FEATURE_LEN

    # Auxiliary targets carried by SampleData.
    # Full-map BFS auxiliary targets are intentionally not stored in SampleData.

    # Environment/action contracts.
    ACTION_NUM = 16
    MOVE_ACTION_NUM = 8
    FLASH_ACTION_NUM = 8
    VALUE_NUM = 1
    MAX_MONSTERS = 2
    MAX_TREASURES = 10
    MAX_BUFFS = 2

    # Model capacity.
    CONV_CHANNEL = 64
    VISUAL_FUSION_DIMS = [64]
    SCALAR_MLP_DIMS = [192, 96]
    VIEW_FUSION_DIMS = [192, 128]
    MAMBA_TBPTT_LEN = 48
    SEQUENCE_ID_PID_MOD = 1000
    SEQUENCE_ID_STRIDE = 10000
    ACTION_PRIOR_WALL_LOGIT = -2.0
    ACTION_PRIOR_MONSTER_ESCAPE_LOGIT = 0.5
    ACTION_PRIOR_FLASH_BASE_LOGIT = -6.0
    ACTION_PRIOR_FLASH_ESCAPE_LOGIT = 1.0
    ACTION_PRIOR_MONSTER_ESCAPE_RADIUS = 7.0
    ACTION_PRIOR_FLASH_DANGER_RADIUS = 6.0
    FLASH_GUARD_ENABLED = False
    FLASH_GUARD_DANGER_BFS = 6.0
    MONSTER_GUARD_ENABLED = False
    MONSTER_GUARD_DANGER_BFS = 12.0
    MONSTER_GUARD_L2_EPS = 0.05
    RESOURCE_OVERRIDE_ENABLED = False
    RESOURCE_OVERRIDE_SAFE_BFS = 9.0
    RESOURCE_OVERRIDE_TRAIN_LOGIT = 0.0
    RESOURCE_OVERRIDE_EXPLORE_GAP = -0.02
    TRAIN_SAMPLE_TOP_K = 16
    TRAIN_SAMPLE_TEMPERATURE = 1.0

    # Normalization and BFS constants.
    BFS_SENTINEL = 1000.0
    GLOBAL_BFS_THRESHOLD = 160.0
    LOCAL_BFS_THRESHOLD = 24.0
    EXPLORE_VECTOR_DANGER_BFS = 4.0
    EXPLORE_VECTOR_SAFE_BFS = 8.0
    EXPLORE_VECTOR_DANGER_SCALE = 0.3
    EXPLORE_VECTOR_FRONTIER_COUNT_NORM = 256.0
    EXPLORE_VECTOR_FEATURE_SCALE = 0.25
    MONSTER_POS_BFS_LOSS_THRESHOLD = 64.0
    MAX_DIST_BUCKET = 5.0
    MAX_FLASH_CD = 100.0
    MAX_BUFF_DURATION = 50.0
    MAX_MONSTER_SPEED = 2.0
    MAX_MONSTER_INTERVAL = 300.0
    MAX_BUFF_REFRESH = 200.0
    MAX_HERO_SPEED = 2.0
    BUFF_COOLDOWN_DEFAULT = 200.0

    # Reward shaping.
    REWARD_CLIP_MIN = -20.0
    REWARD_CLIP_MAX = 30.0
    REWARD_DENSITY_EPS = 1.0e-6
    REWARD_STEP = 0.04
    REWARD_SURVIVE_ALIVE_PER_STEP = 0.03
    REWARD_SCORE_DELTA = 0.04
    REWARD_TREASURE = 8.0
    REWARD_EXPLORE_PER_CELL = 0.05
    REWARD_EXPLORE_APPROACH = 0.08
    REWARD_EXPLORE_VECTOR_ALIGN = 0.04
    PENALTY_EXPLORE_VECTOR_OPPOSE = -0.02
    EXPLORE_VECTOR_REWARD_MIN_STRENGTH = 0.05
    GLOBAL_EXPLORE_TARGET_STEPS = 4 * MAP_SIZE
    GLOBAL_EXPLORE_GAP_CLIP = 0.25
    REWARD_GLOBAL_EXPLORE_ON_TRACK = 0.08
    REWARD_GLOBAL_EXPLORE_AHEAD_COEF = 0.40
    PENALTY_GLOBAL_EXPLORE_LAG_COEF = 1.20
    PENALTY_GLOBAL_EXPLORE_LAG_MAX = -0.35
    REWARD_BUFF_MAINTAIN = 0.01
    REWARD_BUFF_AFTER_500 = 10.0
    REWARD_BUFF_BEFORE_500 = 3.0
    REWARD_MONSTER_BFS_DELTA_POS = 0.12
    REWARD_MONSTER_BFS_DELTA_NEG = 0.18
    REWARD_MONSTER_BFS_DELTA_CLIP = 8.0
    REWARD_MONSTER_PRESSURE_FULL_BFS = 6.0
    REWARD_MONSTER_PRESSURE_ZERO_BFS = 12.0
    REWARD_FLASH_DANGER_BFS_THRESHOLD = 6.0
    REWARD_FLASH_SUCCESS_DELTA = 2.0
    REWARD_FLASH_DANGER_SUCCESS = 3.0
    PENALTY_FLASH_DANGER_FAIL = -0.5
    PENALTY_FLASH_SAFE = -2.0
    REWARD_NO_VISIBLE_MONSTER = 0.03
    REWARD_SAFE_MONSTER_BFS_THRESHOLD = 8.0
    REWARD_SAFE_MONSTER_BFS_CAP = 12.0
    REWARD_SAFE_MONSTER_BFS_COEF = 0.004
    REWARD_DANGER_ESCAPE_THRESHOLD = 8.0
    REWARD_DANGER_ESCAPE_BONUS = 0.4
    REWARD_RESOURCE_SAFE_BFS_HIGH = 10.0
    REWARD_RESOURCE_SAFE_BFS_LOW = 5.0
    REWARD_RESOURCE_DANGER_FACTOR = 0.5
    REWARD_TREASURE_APPROACH = 0.04
    REWARD_BUFF_APPROACH = 0.04
    POST_ESCAPE_SCOUT_STEPS = 64
    POST_ESCAPE_DANGER_BFS = 8.0
    REWARD_POST_ESCAPE_PROGRESS = 0.12
    PENALTY_POST_ESCAPE_REGRESS = -0.12
    POST_ESCAPE_PROGRESS_CLIP = 4.0
    REWARD_SURVIVE_25 = 1.5
    REWARD_SURVIVE_50 = 2.5
    REWARD_SURVIVE_75 = 3.5
    REWARD_SURVIVE_100 = 5.0
    REWARD_SURVIVE_150 = 7.0
    REWARD_SURVIVE_200 = 9.0
    REWARD_SURVIVE_250 = 11.0
    REWARD_SURVIVE_300 = 14.0
    REWARD_SURVIVE_400 = 18.0
    REWARD_SURVIVE_500 = 25.0
    REWARD_SURVIVAL_MILESTONES = (
        (25, REWARD_SURVIVE_25),
        (50, REWARD_SURVIVE_50),
        (75, REWARD_SURVIVE_75),
        (100, REWARD_SURVIVE_100),
        (150, REWARD_SURVIVE_150),
        (200, REWARD_SURVIVE_200),
        (250, REWARD_SURVIVE_250),
        (300, REWARD_SURVIVE_300),
        (400, REWARD_SURVIVE_400),
        (500, REWARD_SURVIVE_500),
    )
    PENALTY_STILL = -0.04
    PENALTY_MOVE_STILL = -0.08
    PENALTY_CONSECUTIVE_STILL_STEP = -0.02
    PENALTY_CONSECUTIVE_STILL_MAX = -0.20
    ANTI_LOOP_WINDOW_STEPS = 10
    ANTI_LOOP_CLOSE_DIST = 2.0
    ANTI_LOOP_NEAR_DIST = 5.0
    ANTI_LOOP_PROGRESS_DIST = 10.0
    PENALTY_ANTI_LOOP_CLOSE = -0.08
    PENALTY_ANTI_LOOP_NEAR = -0.03
    REWARD_ANTI_LOOP_PROGRESS = 0.12
    TRAIL_PROGRESS_WINDOW = 16
    TRAIL_PROGRESS_DIST = 8.0
    TRAIL_STALL_DIST = 4.0
    TRAIL_LOW_UNIQUE_RATIO = 0.45
    REWARD_TRAIL_PROGRESS = 0.08
    PENALTY_TRAIL_STALL = -0.08
    REWARD_OPEN_MOVE_DELTA = 0.04
    PENALTY_OPEN_MOVE_LOSS = -0.05
    OPEN_SPACE_DANGER_BFS = 12.0
    OPEN_SPACE_LOW_NEIGHBORS = 3
    PENALTY_LOW_OPEN_SPACE = -0.10
    PENALTY_NEAR_MONSTER_THRESHOLD = 6.0
    PENALTY_NEAR_MONSTER_SLOPE = 0.06
    PENALTY_CAUGHT = -10.0
    PENALTY_FLASH_ON_CD = -0.5  # 在闪现冷却期间尝试使用闪现的惩罚

    # PPO hyperparameters.
    GAMMA = 0.99
    LAMDA = 0.95
    INIT_LEARNING_RATE_START = 0.00001
    BETA_START = 0.02
    CLIP_PARAM = 0.2
    VALUE_CLIP_PARAM = 2.0
    VF_COEF = 0.5
    GRAD_CLIP_RANGE = 0.5
    ADVANTAGE_NORMALIZE = True
    ADVANTAGE_NORM_EPS = 1.0e-8
    LEARNER_VALIDATE_BATCH = True
    LEARNER_STRICT_BATCH_VALIDATION = False
    LEARNER_VALIDATE_MODEL_OUTPUTS = True
    LEARNER_CUDA_SYNC_DEBUG = False

    TARGET_KL = 0.01
    KL_EARLY_STOP_MULTIPLIER = 1.5

    # Auxiliary losses.
    AUX_MONSTER_POS_COEF = 0.2
    AUX_MONSTER_DIST_COEF = 0.1
    AUX_LOSS_VISIBLE_MONSTER_WEIGHT = 5.0  # 当怪物可见时，辅助损失的额外权重放大系数
